"""create users and user_stats tables

Revision ID: bf81cd1b2ff7
Revises:
Create Date: 2026-06-14 14:21:09.938453

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf81cd1b2ff7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("atcoder_id", sa.String(length=32), nullable=True),
        sa.Column("codeforces_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("atcoder_id"),
        sa.UniqueConstraint("codeforces_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_discord_id"), "users", ["discord_id"], unique=True)
    op.create_table(
        "user_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("coins", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_users_discord_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
