"""add leetcode_id to users

Revision ID: ce038a109e28
Revises: bf81cd1b2ff7
Create Date: 2026-06-14 15:31:13.398130

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce038a109e28"
down_revision: Union[str, Sequence[str], None] = "bf81cd1b2ff7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("leetcode_id", sa.String(length=32), nullable=True))
    op.create_unique_constraint("uq_users_leetcode_id", "users", ["leetcode_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_leetcode_id", "users", type_="unique")
    op.drop_column("users", "leetcode_id")
    # ### end Alembic commands ###
